---
# Source: todo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app.kubernetes.io/name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo
    spec:
      securityContext:
        {}
      containers:
        - name: todo
          securityContext:
            {}
          image: "todo:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http