apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base-local
- namespace.yaml
- ingress.yaml
namespace: dev
images:
- name: todo
  newName: todo
  newTag: latest
replicas:
- count: 2
  name: todo
patchesStrategicMerge:
- patch-deployment.yaml
